### ISSUE TITLE
ProGet Support

### ISSUE THREAD

**Issue by ghost** [james-dibble/ChocolateyExplorer#7]
Unfortunately Chocolatey Explorer doesn't seem to work with my internal Chocolatey repository. I use the free version of Inedo ProGet. I would really appreciate it if you could add support.

Here is the error I'm getting, hopefully it won't be too difficult to fix:
`Loading packages from http://sfoffice2:8888/nuget/snowflake
Failed to load packages from http://sfoffice2:8888/nuget/snowflake
The property 'IsProGetHosted' does not exist on type 'Chocolatey.OData.Service.FeedPackage'. Make   sure to only use property names that are defined by the type.`

Cheers
Sam

**Comment by james-dibble** [comment]
As soon as I can get a test ProGet feed running I'll take a look at adding support

**Comment by james-dibble** [comment]
Fixed with Commit 7be6487f30e20e4b1a52c8348c54b60386512ad2
